[tool.black]
line-length = 80
target-version = ["py310"]

[tool.isort]
line_length = 80
known_future_library = "future"
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
force_grid_wrap = 0
sections = "FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"
default_section = "THIRDPARTY"

